### ISSUE TITLE
failed to start share, reason: invalid directory

### ISSUE THREAD

**Issue by wmbutler** [storj/storjshare-daemon#122] opened 2017-05-05 04:44 UTC
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.5.1, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.7.0
```

### Expected Behavior

Storj daemon should start

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
root@onprem:/documents/storage# storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/979b65eb615b657534136c553b2ad101840ea179.json

  daemon is not running, try: storjshare daemon
root@onprem:/documents/storage# storjshare daemon

  * starting daemon in background
root@onprem:/documents/storage# storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/979b65eb615b657534136c553b2ad101840ea179.json

  failed to start share, reason: invalid directory
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

su - root

1. Ubuntu Xenial
2. apt install snap
3. snap install storjshare
4. storjshare create --sjcx 1MzQowZXqE8yVVRSujxmj9tyUEg7d1CvdM --size 8TB --storage /documents/storage
5. Save file with no edits
6. storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/979b65eb615b657534136c553b2ad101840ea179.json

(See errors above)

- /documents/storage exists and has 8.6TB
- Running as root
- log directory exists

```
/dev/mapper/documents  9.1T   40M  8.6T   1% /documents
```

### config

```
{
  // Set the SJCX/BTC address for receiving contract payments
  "paymentAddress": "1MzQowZXqE8yVVRSujxmj9tyUEg7d1CvdM",
  // Subscribes to the given contract topics
  // See https://storj.github.io/core/tutorial-contract-topics.html
  "opcodeSubscriptions": [
    "0f01020202",
    "0f02020202",
    "0f03020202"
  ],
  // Limits the number of pending OFFER message at one time
  "maxOfferConcurrency": 3,
  // If the seedList is empty, use this bridge to discover seeds
  // Following a transfer, also send an exchange report to this bridge
  "bridgeUri": "https://api.storj.io",
  // Known preferred seeds in form of a storj URI
  // Example: "storj://[ip.or.hostname]:[port]/[nodeid]"
  "seedList": [],
  // Interface to bind RPC server, use 0.0.0.0 for all interfaces or if you 
  // have a public address, use that, else leave 127.0.0.1 and Storj Share
  // will try to determine your address
  "rpcAddress": "127.0.0.1",
  // Port to bind for RPC server, make sure this is forwarded if behind a 
  // NAT or firewall - otherwise Storj Share will try to punch out
  "rpcPort": 4000,
  // Enables NAT traversal strategies, first UPnP, then reverse HTTP tunnel
  // if that fails. Disable if you are public or using dynamic DNS
  "doNotTraverseNat": false,
  // Maximum number of tunnels to provide to the network
  // Tunnels help nodes with restrictive network configurations participate
  "maxTunnels": 3,
  // Maximum number of concurrent connections to allow
  "maxConnections": 150,
  // If providing tunnels, the starting and ending port range to open for 
  // them
  "tunnelGatewayRange": {
    "min": 4001,
    "max": 4003
  },
  // Number of times to retry joining the network and the wait time between
  "joinRetry": {
    "times": 3,
    "interval": 5000
  },
  // Temporarily stop sending OFFER messages if more than this number of shard 
  // transfers are active
  "offerBackoffLimit": 4,
  // ECDSA private key for your network identity, your Node ID is derived from
  // this and it is used to sign and verify messages
  "networkPrivateKey": "readacted",
  // Determines how much detail is shown in the log:
  // 4 - DEBUG | 3 - INFO | 2 - WARN | 1 - ERROR | 0 - SILENT
  "loggerVerbosity": 3,
  // Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid].log
  "loggerOutputFile": "/root/snap/storjshare/6/.config/storjshare/logs/979b65eb615b657534136c553b2ad101840ea179.log",
  // Directory path to store contracts and shards
  "storagePath": "/documents/storage",
  // Amount of space to lease to the network, as human readable string
  // Valid units are B, KB, MB, GB, TB
  "storageAllocation": "8TB",
  // Periodically report your used and free capacity to Storj Labs to improve 
  // the network - no personally identifiable information is sent
  "enableTelemetryReporting": true
}
```

**Comment by PhABC** [comment] 2017-05-09 23:39
Creating the configs folder in /.config/storjshare/ fixes the problem. Seems like not properly created when running ```storjshare create```.

**Comment by jfnz** [comment] 2017-05-10 06:51
That might have fixed it for you, but I get this error:

root@xxxxx:/mount/storj# mkdir /snap/storjshare/6/.config
mkdir: cannot create directory ‘/snap/storjshare/6/.config’: Read-only file system

Any ideas?

**Comment by PhABC** [comment] 2017-05-10 06:55
It seems like snap prevents writing access write. I had this issue once where I couldn't modify anything in snap. Try installing with storjshare with npm and nvm instead.

**Comment by jfnz** [comment] 2017-05-10 06:58
Hmmm.. It looks like it gets created with the wizard but it still doesn't work:

root@xxxxx:~# storjshare create --sjcx <address> --storage /mount/storj --size 1TB --rpcport 31337 --rpcaddress 127.0.0.1 --maxtunnels 10 --tunnelportmin 4000 --tunnelportmax 4010

  * configuration written to /root/snap/storjshare/6/.config/storjshare/configs/xxxxx.json
  * opening in your favorite editor to tweak before running
  ...
  * use new config: storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/xxxxx.json
root@farpho:~# storjshare start --config /root/snap/storjshare/6/.config/storjshare/configs/xxxxx.json

  failed to start share, reason: invalid directory
root@farpho:~# ls /root/snap/storjshare/6/.config/storjshare/configs
xxxxx.json 

I guess I'll try with npm/nvm when I can be bothered.. Getting frustrated now.

**Comment by PhABC** [comment] 2017-05-10 07:03
So the reason why it's invalid is because the folder configs (the last one) does not exist. Go to the path and you will see that only .config/storjshare/shares exists currently. Create the configs file in .config/storjshare and it should work.

**Comment by jfnz** [comment] 2017-05-10 07:30
Okay, have scrapped the snapd packages and moved over to following the nvm/npm guide. Now I have errors for Africa when running "npm install --global storjshare-daemon"

`gyp ERR! configure error 
gyp ERR! stack Error: EACCES, mkdir '/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/weak/build'
gyp ERR! System Linux 4.4.0-75-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/weak
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 

> leveldown@1.6.0 install /root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/leveldown
> prebuild-install || node-gyp rebuild

sh: 1: prebuild-install: Permission denied
gyp ERR! configure error 
gyp ERR! stack Error: EACCES, mkdir '/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/leveldown/build'
gyp ERR! System Linux 4.4.0-75-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/leveldown
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
/root/.nvm/versions/node/v6.10.3/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 (node_modules/storjshare-daemon/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 (node_modules/storjshare-daemon/node_modules/restify/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/storjshare-daemon/node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/root/.nvm/versions/node/v6.10.3/bin/node" "/root/.nvm/versions/node/v6.10.3/bin/npm" "install" "--global" "storjshare-daemon"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.6.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
`
Will go digging :)

**Comment by jfnz** [comment] 2017-05-10 07:55
Okay, not trying to sidetrack this bug but I'm up to having created my config with the storjshare create command, however I get the following:

`xxxx@xxxxx:~$ storjshare start --config /home/xxxx/.config/storjshare/configs/f8966b32df63576d84182417b8c96f9de9fa828e.json

  failed to start share, reason: failed to parse config at /home/xxxx/.config/storjshare/configs/f8966b32df63576d84182417b8c96f9de9fa828e.json`

Any ideas? That file exists and is valid, and is even created by the wizard itself.

**Comment by DaBeSoft** [comment] 2017-05-15 10:26
I am having this issue too ("failed to start share, reason: failed to parse config at"). File is readable, Json is valid. I installed via snap.

Any solutions yet?

**Comment by jfnz** [comment] 2017-05-15 10:29
I was due to format and upgrade from 14.04 to 16.04.02 LTS anyway, doing this and a clean install using the manual method (e.g. nodejs and nvm, etc.) worked fine and it's running great now.

Sorry I don't have an actual fix, but nobody here was of much help so I didn't have many options.

**Comment by DaBeSoft** [comment] 2017-05-15 10:33
Thanks for your blazingly fast reply. I'll try installing via nodejs and nvm too...
(btw, my Ubuntu 16.04 was a fresh install for this)

**Comment by jfnz** [comment] 2017-05-15 10:39
Google for the install guide for nvm, it will install npm for you (or vice versa, I can't remember which is which). Just make sure you have all the dependencies before beginning. You'll also need to manually create the config directory as the installer fails to for some reason.. that's /home/user/.config/storjshare... etc.

Sorry for being vague, just replying on my phone and don't have the guides in front of me.

**Comment by DaBeSoft** [comment] 2017-05-15 11:49
Just checking back in to report that it works now. i reinstalled ubuntu 16.04 to start of a clean base and installed storjshare-daemon using nvm, nodejs (6.9.0) and npm. Thanks for your help!

**Comment by bookchin** [comment] 2017-05-15 15:19
It looks like this could be related to how snapd does isolation/permissions? I'll reach out to our friends at Canonical who helped us publish via snap to see if there is something we are missing.

**Comment by geckogecko** [comment] 2017-05-18 11:23
I am having the exact same issue when installing the daemon via snap (on ubuntu 14.04 and 16.04)

**Comment by mariobaldini** [comment] 2017-05-31 08:33
I'm having the same problem in Debian 9.0 stretch. 
Installed from snap: `sudo snap install storjshare --edge`

Daemon runs fine (accepts and logs status requests). 

But storjshare start fails: 
'''
storjshare start --config /home/xxxx/snap/storjshare/5/.config/storjshare/configs/xxxxa99bc84c43a41323.json

  failed to start share, reason: invalid directory
'''

But I do have a 'configs' folder (created automatically) in '~/snap/storjshare/5/.config/storjshare'. 
My target storage directory exists and has +rw permissions. 

Is it possible to fix this snap installation without reinstalling from other methods? 

Also, in the config file, the target directory needs an tailing / in the path? (I already tried with/without it, without success)

Thanks

**Comment by jfnz** [comment] 2017-05-31 09:24
Using snap is poked. Just install manually, that's the only way I could get it working.

**Comment by mariobaldini** [comment] 2017-05-31 09:44
Just did that... with the same results. :/ 

Steps: 
- sudo snap remove storjshare
- Manual installation following the guide https://github.com/Storj/storjshare-daemon/
```
sudo apt install git build-essential python2.7
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
nvm install --lts
```

It installed fine, I supose. I'm able to query the daemon status. 

Created a new config... tried to start.. 
```
storjshare start --config /home/mario/.config/storjshare/configs/xxxx29876e8320de5f15fa2a0.json

  failed to start share, reason: invalid directory
```
I increased the verbosity in the config file (to 4), but get the same log/error. 

Is it possible to increase the log detail of the storjshare start command? 
I don't know why but in this new installation (manual) it's not logging to the suposed location (in the config file): `/home/mario/.config/storjshare/logs`

**Comment by mariobaldini** [comment] 2017-06-01 14:32
Could get it working by installing node from the official repo/commands (newer version), and not the commands in the storj guide. 

- remove snap, node, storj, etc...
- Install latest node 6.x
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```
- Istall storj, with sudo
```
sudo npm install --global storjshare-daemon
```

**Comment by kim0** [comment] 2017-06-13 12:32
It seems I could get it working by
```
snap run --shell storjshare
cd /home/kim0/snap/storjshare/22
mkdir -p .config/storjshare/configs/
exit
storjshare create --sjcx mywallet --storage /mnt/
```

**Comment by fnc12** [comment] 2017-06-15 07:02
facing the issue too. Installed from `npm`

**Comment by benlake** [comment] 2017-06-18 03:29
@kim0 Thank you for a post actually related to the stated issue.

This error shows up with the use of --outfile as well, and I was not able to overcome the issue via the --shell technique. I instead dropped --outfile, let the files get created in ~/.config and moved them after the fact.

**Comment by benlake** [comment] 2017-06-19 13:13
Based on the OPs snap path, he was running version 6. I was running version 22 when I encountered this problem. How have there been so many versions that don't function?

While I was able to get the config files created, 'storjshare start' was still unsuccessful due to the "invalid directory" error, referring to the storj share directory. I'm pretty sure this is a snap sandboxing issue; I'm not sure how this daemon would ever work without a means to provide additional file permissions to the snap; outside of the snap path. Symlinks don't fool the sandboxer :D

**Comment by pjmelvin** [comment] 2017-06-27 06:19
Having the same problem... the directory exists, the permissions are set. Is there a better logging system? I changed from 3 to 4 in the config

**Comment by pjmelvin** [comment] 2017-06-27 06:33
There is a file referenced in the create generated config file that refers to the target disk allocation location. It appends the '/storj.io/' to the end of the location specified in the create command. This needs to be created... then it will work

**Comment by rouben** [comment] 2017-10-13 08:40
Don't think this is a bug per se... the issue is that the snap subsystem restricts access to certain paths, even if permissions are OK. If you're familiar with docker, think of how you have to tell docker to map certain paths on the host system to paths inside the docker container, otherwise any process run inside the container will not be able to see any paths outside of the container (i.e. on the host itself). Similar deal with snaps. According to snap docs, there doesn't seem to be a trivial way to allow a particular snap access outside of its "jail". So really this bug should be filed against the "snap" packager of storjshare, not the storjshare project itself.

Basically, the storjshare snap has "not sane" defaults, making it impossible to use the snap out of the box. I'm trying to figure out whether or not it's feasible to do this, and if yes, how exactly...

If you want to see what I mean, try this as the user you normally run storj with:
```
snap run --shell storjshare
cd
pwd

```
Normally `pwd` would return `/home/xxx/`, but in this case, it will return something like `/home/xxx/snap/storjshare/yy/` which is NOT the normal home directlory. Now try going to your storj storage directory, reading your JSON config file, or just anything normal... see what I mean?

Anyway, the answer probably lies with setting up an interface (think docker path maps). They're documented [here](https://docs.snapcraft.io/reference/interfaces) and quite frankly the most promising one so far appears to be the one allowing access to /media mounts... 

Since the "home" permission is given to this snap by default, one way to address this, is move your storj user's home directory onto the same volume as your storage, and just have everything (config, logs, storage path) under .config/storjshare/ which actually storjshare does by default anyway. Going to try this next... it's annoying, but I think it will work.

**Comment by tempestb** [comment] 2017-10-25 19:30
Rouben's answer seems to have settled this one with a solution.  I have added this to my unofficial storj FAQ here ->  http://storjish.blogspot.com/2017/10/why-do-i-get-this-error-in-snap-failed.html

And we can migrate that to a proper STORJ FAQ when we have one for issues like this.  In the meantime, this issue can probably be closed.

**Comment by rouben** [comment] 2017-10-25 21:55
Update: I got the snap to work just fine by placing the config, logs and storage all under /home. Like so:
`/home/storj/` - home dir for the storjshare daemon user
`home/storj/storjshare/configs/storjshare-config.json` - config file for my miner node (I run just one node)
`home/storj/storjshare/logs/` - log directory
`/home/storj/storjdata` - mountpoint for my storj disk - not the best setup, admittedly, but it works and keep the snap happy

**Comment by RichardLitt** [comment] 2018-10-30 12:35
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:35 UTC
Labels: shard storage
