### ISSUE TITLE
Storjshare daemon crashes when node runs out of storage.

### ISSUE THREAD

**Issue by Techwolf12** [Storj/storjshare-daemon#241] opened 2017-08-30 14:16 UTC
### Package Versions

```
daemon: 3.5.5, core: 6.8.0, protocol: 1.1.0
```

### Node version

```
v6.11.1
```
### Expected Behavior

The node should be stopped, the daemon should not crash

### Actual Behavior
The daemon crashes when my disk space ran out on one mount (It had 4gb of logs)

```
Daemon log:
{"level":"info","message":"share <NODE ID>exited with code 1","timestamp":"2017-08-30T14:07:16.543Z"}
```

### Steps to Reproduce

1. Let diskspace run out on a node's mount
2. daemon should now crash every time you try to load that node

**Comment by AleksandrGoriachev** [comment] 2017-09-15 11:03
The same problem we encountered with 7.0.3:
{"lastSeen":"2017-09-14T06:22:24.695Z","port":4001,"address":"188.64.168.51","userAgent":"7.0.3","protocol":"1.2.0","responseTime":1018.6440363532726,"lastTimeout":"2017-09-09T02:57:17.579Z","timeoutRate":0,"nodeID":"39a4ea0b5b5fd4c5d2ba0df326292629ea0cbe38"}

**Comment by AleksandrGoriachev** [comment] 2017-09-15 11:04
And this case is not only one, at least 3 nodes are down now! ? More than 1,6TB have lost!

**Comment by Techwolf12** [comment] 2017-09-18 06:09
Are you running on Linux? 
If so, please run `df` and output the disk size, then run du -c on the mount and report the sharddata.kfs folder and the total, then, give your storageAllocation value in your config.json

**Comment by braydonf** [comment] 2017-09-18 18:25
So I've loaded about 16 farmers in a test environment with over 1GB each, and then lowered the allocation space to 1GB or less, and I'm unable to get the nodes to crash. The nodes will just stop sending OFFERs as intended.

**Comment by Techwolf12** [comment] 2017-09-18 20:46
@braydonf Try setting the partition space to 2 gb and storj to 1.8 gb

**Comment by braydonf** [comment] 2017-09-18 22:31
Okay, I'll try that.

**Comment by braydonf** [comment] 2017-09-19 18:08
Okay, so I partitioned a device with 2GB:
```
/dev/sda1                    1.9G  1.8G     0 100% /media/share
```
And then set the shared size to 1.8GB:
```
  "storageAllocation": "1.8GB"
```

And was able to reproduce the crash:
```
9|farmer-1 | events.js:160
9|farmer-1 |       throw er; // Unhandled 'error' event
9|farmer-1 |       ^
9|farmer-1 | OpenError: IO error: /data/contracts.db/000007.ldb: No space left on device
9|farmer-1 |     at /root/node_modules/levelup/lib/levelup.js:117:34
9|farmer-1 |     at /root/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

**Comment by braydonf** [comment] 2017-09-19 19:18
To prevent hitting this https://github.com/Storj/core/pull/730

**Comment by braydonf** [comment] 2017-09-21 23:52
Fixed in https://github.com/Storj/core/releases/tag/v8.0.0

**Closed by braydonf** 2017-09-21 23:52 UTC

**Comment by Techwolf12** [comment] 2017-09-22 06:18
Whoo! Thanks for the time and effort @braydonf!
