### ISSUE TITLE
Feature request: Node window to background + real time status table update.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#54] opened 2017-01-31 23:50 UTC
1- A few users on rocketchat have requested the ability to hide the node window from the taskbar in windows, meaning that they want the node to run in the background. This could be done with something like `storjshare --background`.
2- We have had some requests to make the `storjshare status` output dynamic, meaning that the data in the table is updated in real time. This could be done with something like `storjshare status --dynamic`.

**Comment by MeijeSibbel** [comment] 2017-01-31 23:52
I guess (1) is related to: https://github.com/Storj/storjshare-daemon/issues/9

**Comment by crazyearner** [comment] 2017-01-31 23:54
Perfect nodes run in background status available using status command :)

**Comment by bookchin** [comment] 2017-02-05 01:41
Number 1 is a duplicate of #9 and for number 2, I'd rather not introduce the complexity needed to redraw the terminal output when you can just use:

```
watch -n [interval seconds] storjshare status
```

**Closed by bookchin** 2017-02-05 01:41 UTC
