### ISSUE TITLE
Update snap channels

### ISSUE THREAD

**Issue by asymmetric** [Storj/storjshare-daemon#184] opened 2017-07-02 17:09 UTC
### Expected Behavior

`snap info storjshare` should show more recent versions on the `candidate` and `beta` channels.

### Actual Behavior

```
asymmetric@vps418113:~$ snap info storjshare
name:      storjshare
summary:   "farm data on the Storj network."
publisher: bookchin
description: |
  Earn money by sharing your hard drive space.
  Daemon + CLI for farming data on the Storj network.
  
channels:                       
  latest/stable:    3.1.0  (22) 28MB -
  latest/candidate: 2.5.1  (11) 27MB -
  latest/beta:      2.5.1  (11) 27MB -
  latest/edge:      master (5)  27MB -

```

### Steps to Reproduce

1. `snap info storjshare`

**Comment by aleitner** [comment] 2017-07-06 19:13
this is a duplicate of #171

**Closed by aleitner** 2017-07-06 19:13 UTC
