### ISSUE TITLE
Consider distributing a binary executable via pkg builder

### ISSUE THREAD

**Issue by trashhalo** [storj/storjshare-daemon#238] opened 2017-08-24 17:28 UTC
### Expected Behavior

I can download a executable for my platform. 

### Actual Behavior
I have to follow a series of steps to build libs and python node etc etc. 

### How??
https://github.com/zeit/pkg let's you build bundle node apps into executables. Also supports cross compiling native dependencies.

**Comment by jfnz** [comment] 2017-09-05 05:52
Go one step further -- If I could just "apt-get install storjshare" and use a text-based menu system to configure it and see status, etc. for headless installs that would be absolutely ideal.

**Comment by tempestb** [comment] 2017-10-25 17:06
We use Snap for this.  The problem is manpower to keep it updated and ready to go.  Storj is adding more developers soon, but they are still aggressively hiring to fill in the blanks.  They basically need someone to manage the snap packages and have them updated when there are changes.  It's just a bit difficult right now, but hopefully in the future it'll be fixed up.

That said, if Snap doesn't solve the problem, I could look into pkg and see about working on it myself, but I don't want to be redundant if Snap is already a solution that we're familiar and happy with.

**Comment by sebastianheyn** [comment] 2018-01-29 21:05
snap sucks if you dont use ubuntu. where is the issue in distributing  a statically linked binary file?

**Comment by zannen** [comment] 2018-02-08 21:39
See also https://hub.docker.com/r/oreandawe/storjshare-cli/ for a Docker container of the storj daemon. [Full disclosure: zannen==oreandawe]

**Comment by RichardLitt** [comment] 2018-10-30 12:35
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:35 UTC
Labels: build
