### ISSUE TITLE
Add option to remove node

### ISSUE THREAD

**Issue by kznamst** [Storj/storjshare-daemon#167] opened 2017-06-17 14:12 UTC
Here's an idea that can be implemented to storjshare-daemon:
Lets say i have a node and don't want to keep it anymore. Right now i could close it and be done with it, but there may be another way to make this smoother, lets say we add another feature called "End node"(or something similar) that will get all data from the node and send it to other nodes(creating new contracts), so it won't get lost(I also know that the data is uploaded on 6 different nodes, but sometimes all 6 nodes may go down).
Also this way our reputation won't get lost(I've read somewhere that storj will also implement a reputation system for farmers).
What do you guys think?

**Comment by JukeboxRhino** [comment] 2017-06-25 01:16
This would require changes in the bridge and to the protocol, but I agree that this would be a good idea.

**Comment by QzSG** [comment] 2017-07-07 10:03
Currently the way to go is setting said node to '0' space allocation and waiting 3 months for all existing contracts to expire.

**Comment by tempestb** [comment] 2017-10-25 18:22
The problem is that each node's data is encrypted, and the other node can't use it because it uses a different key.  Security.  There is also a host of current architectural issues that would make this rather difficult.  Now that Reed Solomon is in place we shouldn't be concerned about merging nodes.   A node operator can either kill the node, or set the 0 to space allocation and slowly retire it.   

I suggest we close this.

**Closed** 2017-10-26 00:11 UTC
